repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # the release, git tag, or commit you want to use
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
